apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    controller-tools.k8s.io: "1.0"
    openshift.io/run-level: "1"
  name: openshift-cloud-credential-operator
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: openshift-cloud-credential-operator
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  replicas: 1
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      containers:
      - env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        image: quay.io/openshift/origin-cloud-credential-operator:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 150Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        command:
          - /root/manager
          - --log-level
          - debug
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 10
