apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  annotations:
    config.openshift.io/inject-proxy: "manager"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  replicas: 1
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      containers:
      - env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        image: quay.io/openshift/origin-cloud-credential-operator:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        command:
          - /root/manager
          - --log-level
          - debug
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: cco-trusted-ca
          mountPath: /etc/pki/ca-trust/extracted/pem/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cco-trusted-ca
        configMap:
          optional: true
          name: cco-trusted-ca
          items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    # This label ensures that the OpenShift Certificate Authority bundle
    # is added to the ConfigMap.
    config.openshift.io/inject-trusted-cabundle: "true"
  name: cco-trusted-ca
  namespace: openshift-cloud-credential-operator
