apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloud-credential-operator-alerts
  namespace: openshift-cloud-credential-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  groups:
  - name: CloudCredentialOperator
    rules:
    - alert: CloudCredentialOperatorTargetNamespaceMissing
      expr: cco_credentials_requests_conditions{condition="MissingTargetNamespace"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: CredentialsRequest(s) pointing to non-existant namespace
    - alert: CloudCredentialOperatorProvisioningFailed
      expr: cco_credentials_requests_conditions{condition="CredentialsProvisionFailure"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: CredentialsRequest(s) unable to be fulfilled
    - alert: CloudCredentialOperatorDeprovisioningFailed
      expr: cco_credentials_requests_conditions{condition="CredentialsDeprovisionFailure"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: CredentialsRequest(s) unable to be cleaned up
    - alert: CloudCredentialOperatorInsufficientCloudCreds
      expr: cco_credentials_requests_conditions{condition="InsufficientCloudCreds"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: Cluster's cloud credentials insufficient for minting or passthrough
    - alert: CloudCredentialOperatorDown
      expr: absent(up{job="cco-metrics"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        message: cloud-credential-operator pod not running
