apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
spec:
  endpoints:
  - interval: 30s
    port: cco-metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - openshift-cloud-credential-operator
  selector: {}
