apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: credentialsrequests.credminter.openshift.io
spec:
  group: credminter.openshift.io
  names:
    kind: CredentialsRequest
    plural: credentialsrequests
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterID:
              type: string
            clusterName:
              type: string
            providerSpec:
              type: object
            secretRef:
              type: object
          required:
          - clusterName
          - clusterID
          - secretRef
          type: object
        status:
          properties:
            lastSyncGeneration:
              format: int64
              type: integer
            lastSyncTimestamp:
              format: date-time
              type: string
            providerStatus:
              type: object
            provisioned:
              type: boolean
          required:
          - provisioned
          - lastSyncGeneration
          type: object
      required:
      - spec
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
