apiVersion: cloudcredential.openshift.io/v1beta1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-cluster-api
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: aws-cloud-credentials
    namespace: openshift-cluster-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1beta1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:DescribeImages
      - ec2:DescribeVpcs
      - ec2:DescribeSubnets
      - ec2:DescribeAvailabilityZones
      - ec2:DescribeSecurityGroups
      - ec2:RunInstances
      - ec2:DescribeInstances
      - ec2:TerminateInstances
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:DescribeLoadBalancers
      - elasticloadbalancing:DescribeTargetGroups
      - elasticloadbalancing:RegisterTargets
      resource: "*"
---
