apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cloud-credential-webhook-operator-rolebinding
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-credential-webhook-operator-role
subjects:
- kind: ServiceAccount
  name: cloud-credential-webhook-operator
  namespace: openshift-cloud-credential-operator
