apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-credential-webhook-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
