apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: pod-identity-webhook
        namespace: openshift-cloud-credential-operator
        path: /mutate-v1-pod
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: pod-identity-webhook.azure.mutate.io
    objectSelector:
      matchLabels:
        azure.workload.identity/use: "true"
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
